---
title: 42Lab
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://42Lab.io
baseurl: "/42Lab/"
email: data@9lab.co
description: First Portable Hardware Platform for Biotech Experiments
people:
- name: Dr.Data Ng
  pic: 1
  position: Co-founder and CEO
  social:
  - title: twitter
    url: https://twitter.com/Data_ng
  - title: linkedin
    url: https://hk.linkedin.com/in/datackng
- name: Miss Yasaman Nematbakhsh
  pic: 1
  position: Co-founder and Chief Scientific Officer
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/yasaman-nemat-4b630898/
social:
- title: twitter
  url: http://twitter.com/42LabBio
address:
- line: 10/F, Cheung Hing Industrial Building,
- line: 12P Smithfield, Kennedy Town, HKSAR
markdown: kramdown
permalink: pretty
